name: Executar Testes Robot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências Node.js e construir aplicação
        run: |
          npm install
          npm run build

      - name: Instalar navegador e driver
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb libnss3
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome*.deb || sudo apt -f install -y
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/138.0.7204.92/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Executar testes com Xvfb (modo headless)
        run: |
          Xvfb :99 & export DISPLAY=:99
          cd dist
          python3 -m http.server 8000 &
          cd ..
          sleep 2
          robot --variable LOGIN_PAGE:http://localhost:8000/ --variable REGISTER_PAGE:http://localhost:8000/ tests

      - name: Salvar relatório
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: |
            log.html
            report.html
            output.xml
