name: Simple Jira Update on Push

on: push

jobs:
  add_comment_to_jira:
    name: Add Comment to Jira Issue
    runs-on: ubuntu-latest
    steps:
      - name: Extract and Debug Issue Key
        id: extract_key
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          echo "Branch name: $BRANCH_NAME"
          echo "Commit message: $COMMIT_MSG"

          # Extract Jira issue key from branch name (assuming format like AC-123)
          if [[ $BRANCH_NAME =~ ([A-Z]+-[0-9]+) ]]; then
            ISSUE_KEY=${BASH_REMATCH[1]}
          # If branch is main, try to extract from commit message (for merge commits)
          elif [[ $BRANCH_NAME == "main" && $COMMIT_MSG =~ ([A-Z]+-[0-9]+) ]]; then
            ISSUE_KEY=${BASH_REMATCH[1]}
            echo "Extracted issue key from commit message"
          else
            ISSUE_KEY=$BRANCH_NAME
          fi

          echo "Extracted issue key: $ISSUE_KEY"
          echo "issue_key=$ISSUE_KEY" >> $GITHUB_OUTPUT

      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Add Comment to Jira
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ steps.extract_key.outputs.issue_key }}
          comment: |
            Automated comment from GitHub Actions:
            A push was made to branch: `${{ github.ref_name }}`
            Last commit message: `${{ github.event.head_commit.message }}`
            Pushed by: `${{ github.actor }}`
            See commit details: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
